// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Customer.proto
// Protobuf Java Version: 4.27.2

package com.example.restapi;

public interface CustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:restapi.Customer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>required string firstName = 2;</code>
   * @return Whether the firstName field is set.
   */
  boolean hasFirstName();
  /**
   * <code>required string firstName = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>required string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>required string lastName = 3;</code>
   * @return Whether the lastName field is set.
   */
  boolean hasLastName();
  /**
   * <code>required string lastName = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>required string lastName = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
