// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Customer.proto
// Protobuf Java Version: 4.27.2

package com.example.restapi;

public interface CustomersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:restapi.Customers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .restapi.Customer customer = 1;</code>
   * @return Whether the customer field is set.
   */
  boolean hasCustomer();
  /**
   * <code>required .restapi.Customer customer = 1;</code>
   * @return The customer.
   */
  com.example.restapi.Customer getCustomer();
  /**
   * <code>required .restapi.Customer customer = 1;</code>
   */
  com.example.restapi.CustomerOrBuilder getCustomerOrBuilder();
}
