// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Customer.proto
// Protobuf Java Version: 4.27.2

package com.example.restapi;

/**
 * Protobuf type {@code restapi.Customers}
 */
public final class Customers extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:restapi.Customers)
    CustomersOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Customers.class.getName());
  }
  // Use Customers.newBuilder() to construct.
  private Customers(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Customers() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.restapi.CustomerProtos.internal_static_restapi_Customers_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.restapi.CustomerProtos.internal_static_restapi_Customers_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.restapi.Customers.class, com.example.restapi.Customers.Builder.class);
  }

  private int bitField0_;
  public static final int CUSTOMER_FIELD_NUMBER = 1;
  private com.example.restapi.Customer customer_;
  /**
   * <code>required .restapi.Customer customer = 1;</code>
   * @return Whether the customer field is set.
   */
  @java.lang.Override
  public boolean hasCustomer() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .restapi.Customer customer = 1;</code>
   * @return The customer.
   */
  @java.lang.Override
  public com.example.restapi.Customer getCustomer() {
    return customer_ == null ? com.example.restapi.Customer.getDefaultInstance() : customer_;
  }
  /**
   * <code>required .restapi.Customer customer = 1;</code>
   */
  @java.lang.Override
  public com.example.restapi.CustomerOrBuilder getCustomerOrBuilder() {
    return customer_ == null ? com.example.restapi.Customer.getDefaultInstance() : customer_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasCustomer()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getCustomer().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCustomer());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCustomer());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.restapi.Customers)) {
      return super.equals(obj);
    }
    com.example.restapi.Customers other = (com.example.restapi.Customers) obj;

    if (hasCustomer() != other.hasCustomer()) return false;
    if (hasCustomer()) {
      if (!getCustomer()
          .equals(other.getCustomer())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCustomer()) {
      hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
      hash = (53 * hash) + getCustomer().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.restapi.Customers parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.restapi.Customers parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.restapi.Customers parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.restapi.Customers parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.restapi.Customers parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.restapi.Customers parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.restapi.Customers parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.restapi.Customers parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.restapi.Customers parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.restapi.Customers parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.restapi.Customers parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.restapi.Customers parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.restapi.Customers prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code restapi.Customers}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:restapi.Customers)
      com.example.restapi.CustomersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.restapi.CustomerProtos.internal_static_restapi_Customers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.restapi.CustomerProtos.internal_static_restapi_Customers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.restapi.Customers.class, com.example.restapi.Customers.Builder.class);
    }

    // Construct using com.example.restapi.Customers.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getCustomerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      customer_ = null;
      if (customerBuilder_ != null) {
        customerBuilder_.dispose();
        customerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.restapi.CustomerProtos.internal_static_restapi_Customers_descriptor;
    }

    @java.lang.Override
    public com.example.restapi.Customers getDefaultInstanceForType() {
      return com.example.restapi.Customers.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.restapi.Customers build() {
      com.example.restapi.Customers result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.restapi.Customers buildPartial() {
      com.example.restapi.Customers result = new com.example.restapi.Customers(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.restapi.Customers result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.customer_ = customerBuilder_ == null
            ? customer_
            : customerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.restapi.Customers) {
        return mergeFrom((com.example.restapi.Customers)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.restapi.Customers other) {
      if (other == com.example.restapi.Customers.getDefaultInstance()) return this;
      if (other.hasCustomer()) {
        mergeCustomer(other.getCustomer());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasCustomer()) {
        return false;
      }
      if (!getCustomer().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCustomerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.example.restapi.Customer customer_;
    private com.google.protobuf.SingleFieldBuilder<
        com.example.restapi.Customer, com.example.restapi.Customer.Builder, com.example.restapi.CustomerOrBuilder> customerBuilder_;
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     * @return Whether the customer field is set.
     */
    public boolean hasCustomer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     * @return The customer.
     */
    public com.example.restapi.Customer getCustomer() {
      if (customerBuilder_ == null) {
        return customer_ == null ? com.example.restapi.Customer.getDefaultInstance() : customer_;
      } else {
        return customerBuilder_.getMessage();
      }
    }
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     */
    public Builder setCustomer(com.example.restapi.Customer value) {
      if (customerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        customer_ = value;
      } else {
        customerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     */
    public Builder setCustomer(
        com.example.restapi.Customer.Builder builderForValue) {
      if (customerBuilder_ == null) {
        customer_ = builderForValue.build();
      } else {
        customerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     */
    public Builder mergeCustomer(com.example.restapi.Customer value) {
      if (customerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          customer_ != null &&
          customer_ != com.example.restapi.Customer.getDefaultInstance()) {
          getCustomerBuilder().mergeFrom(value);
        } else {
          customer_ = value;
        }
      } else {
        customerBuilder_.mergeFrom(value);
      }
      if (customer_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     */
    public Builder clearCustomer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      customer_ = null;
      if (customerBuilder_ != null) {
        customerBuilder_.dispose();
        customerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     */
    public com.example.restapi.Customer.Builder getCustomerBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCustomerFieldBuilder().getBuilder();
    }
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     */
    public com.example.restapi.CustomerOrBuilder getCustomerOrBuilder() {
      if (customerBuilder_ != null) {
        return customerBuilder_.getMessageOrBuilder();
      } else {
        return customer_ == null ?
            com.example.restapi.Customer.getDefaultInstance() : customer_;
      }
    }
    /**
     * <code>required .restapi.Customer customer = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.restapi.Customer, com.example.restapi.Customer.Builder, com.example.restapi.CustomerOrBuilder> 
        getCustomerFieldBuilder() {
      if (customerBuilder_ == null) {
        customerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.restapi.Customer, com.example.restapi.Customer.Builder, com.example.restapi.CustomerOrBuilder>(
                getCustomer(),
                getParentForChildren(),
                isClean());
        customer_ = null;
      }
      return customerBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:restapi.Customers)
  }

  // @@protoc_insertion_point(class_scope:restapi.Customers)
  private static final com.example.restapi.Customers DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.restapi.Customers();
  }

  public static com.example.restapi.Customers getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Customers>
      PARSER = new com.google.protobuf.AbstractParser<Customers>() {
    @java.lang.Override
    public Customers parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Customers> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Customers> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.restapi.Customers getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

